# Generated by Django 2.2.14 on 2022-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220824_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.CharField(choices=[('togo', 'Togo'), ('benin', 'Bénin'), ('cotedivoire', "Cote d'ivoire"), ('cameroun', 'Cameroun'), ('mali', 'Mali'), ('niger', 'Niger'), ('senegal', 'Sénégal')], default='togo', max_length=30),
        ),
    ]
