# Generated by Django 2.2.14 on 2022-08-26 17:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(default='togo', max_length=2),
        ),
    ]
